BIN_NAME = runner
SRC_PATH = .
# If using flex and bison, set prefix here so *.l and *.y files can be processed
FLEX_PREFIX = scr
# pkg-config libraries
LIBS =
## ncurses menu form sqlite3 etc, see pkg-config --list-all for all of them
# General compilation flags
COMPILE_FLAGS = -Wall -Wextra -g
# Includes
INCLUDES = -I $(SRC_PATH)
# Installation prefix
PREFIX = /usr/local
# man page directory
MAN_DIR = $(PREFIX)/man/man1
# Extension of the source files.
SRC_EXT = c

# This makefile is a simplified version of the generic makefile on GitHub,
# modified to handle flex and bison files as well.
# Use find to get all of the C files in the src directory that are not
# generated by flex or bison.
SOURCES = $(shell find $(SRC_PATH) -name '*.$(SRC_EXT)' -printf '%T@\t%p\n' \
				| sort -k 1nr | cut -f2- | grep -v ".lex." | grep -v ".tab.")

# Sources that will be passed to flex
FLEX_SRCS = $(shell find $(SRC_PATH) -name '*.l' -printf '%T@\t%p\n' \
				| sort -k 1nr | cut -f2-)

FLEX_OUTPUTS = lex.$(FLEX_PREFIX).c
FLEX_OBJECT = $(BUILD_PATH)/lex.$(FLEX_PREFIX).o

# Bison sources.
BISON_SRCS = $(shell find $(SRC_PATH) -name '*.y' -printf '%T@\t%p\n' \
				| sort -k 1nr | cut -f2-)

BISON_OUTPUTS = $(BISON_SRCS:$(SRC_PATH)/%.y=%.tab.c) # bison generated c file
GRAMMAR_TAB = $(BISON_SRCS:$(SRC_PATH)/%.y=%.tab.c)   # bison generated c file for compilation
BISON_OUTPUTS := $(BISON_SRCS:$(SRC_PATH)/%.y=%.tab.h) # bison generated header file
BISON_OBJ = $(BISON_SRCS:$(SRC_PATH)/%.y=$(BUILD_PATH)/%.tab.o) # resulting object file
OBJECTS = $(SOURCES:$(SRC_PATH)/%.$(SRC_EXT)=$(BUILD_PATH)/%.o) # object files from regular source files
DEPS = $(OBJECTS:.o=.d)

export BUILD_PATH = build
export BIN_PATH = bin

all: dirs $(BISON_OBJ) $(FLEX_OBJECT)
	@echo "Compiling..."
	@make compile --no-print-directory

install:
	@echo Installing to $(PREFIX)/bin
	install $(BIN_PATH)/$(BIN_NAME) $(PREFIX)/bin
	@echo Installing manual page.
	cp ./runner.1 $(MAN_DIR)

uninstall:
	@echo Uninstalling
	$(RM) $(PREFIX)/bin/$(BIN_NAME)

$(BISON_OBJ): $(BISON_OUTPUTS)
	$(CC) $(CFLAGS) -c $(GRAMMAR_TAB) -o $@

$(FLEX_OBJECT): $(FLEX_OUTPUTS)
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: dirs
dirs:
	@echo "Creating build and bin directories"
	@mkdir -p $(dir $(OBJECTS))
	@mkdir -p $(BIN_PATH)

compile: $(BIN_PATH)/$(BIN_NAME) $(BISON_OUTPUTS) $(FLEX_OUTPUTS)
	@echo "Making symlink: $(BIN_NAME) -> $<"
	@$(RM) $(BIN_NAME)
	@ln -s $(BIN_PATH)/$(BIN_NAME) $(BIN_NAME)

$(BISON_OUTPUTS): $(BISON_SRCS)
	@echo "Compiling grammar..."
	bison -d -Wcounterexamples $(BISON_SRCS)

$(FLEX_OUTPUTS): $(FLEX_SRCS)
	@echo "Compiling scanner..."
	flex $(FLEX_SRCS)

$(BIN_PATH)/$(BIN_NAME): $(OBJECTS)
	@echo "Linking: $@"
	$(CC) $(OBJECTS) $(BISON_OBJ) $(FLEX_OBJECT) $(LDFLAGS) -o $@

#Include dependency files.
-include $(DEPS)

$(BUILD_PATH)/%.o: $(SRC_PATH)/%.$(SRC_EXT)
	@echo "Compiling: $< -> $@"
	$(CC) $(CFLAGS) $(INCLUDES) -MP -MMD -c $< -o $@

clean:
	@echo "Deleting $(BIN_NAME) symlink"
	@$(RM) $(BIN_NAME)
	@echo "Deleting directories"
	@$(RM) -r build
	@$(RM) -r bin
	@$(RM) -f $(FLEX_OUTPUTS) $(BISON_OUTPUTS) $(GRAMMAR_TAB)
